[theme]
primaryColor="#FF4B4B"
backgroundColor="#1E1E1E"  # Dark background
secondaryBackgroundColor="#282828"  # Slightly lighter dark background
textColor="#FFFFFF"  # Light text color
font="sans serif"
